name = "JITrench"
uuid = "573e55e6-eb53-4bcf-a884-6670806246ed"
authors = ["Yuchi Yamaguchi"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
